### ISSUE TITLE
About the motivation

### ISSUE THREAD

**Issue by thautwarm** [ICEYSELF/Love-Lang#1]
Is this for your girl friend? As a memorial or something else?

**Comment by ICEYSELF** [comment]
None of the above. 

--------------原始邮件--------------
发件人："Taine Zhao "<notifications@github.com>;
发送时间：2019年8月17日(星期六) 晚上8:02
收件人："ICEYSELF/Love-Lang" <Love-Lang@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[ICEYSELF/Love-Lang] About the motivation (#1)
-----------------------------------

 
Is this for your girl friend? As a memorial or something else?

**Comment by ICEYSELF** [comment]
ckxc-v2 is for my girlfriend, it is now hosted on [bitbucket](bitbucket.org/iceycream/ckxc-v2). This is for [another project](github.com/himself65/LianXue).
